/**
 * ProteinTrackerLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/02/2016
 */

var configuration = {
    //The base Uri for API calls
    BASEURI : "https://proteintrackerapi.azurewebsites.net"

};

module.exports = configuration;

